name: Python package

on: [push]

jobs:
  test:
    name: Test MechWolf on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  lint:
    name: Lint the source code with Flake8
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Lint the source code with Flake8
        run: |
          pip install flake8
          flake8
  style-check:
    name: Ensure code style compliance with Black
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Ensure code style compliance with Black
        run: |
          pip install black
          black --check mechwolf
  type-check:
    name: Typecheck with Mypy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Typecheck with Mypy
        run: |
          pip install mypy
          mypy mechwolf/ --ignore-missing-import --no-implicit-optional

  build-docs:
    name: Verify documentation builds
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Build the actual docs
        run: |
          cd docs
          npm i
          npm run build
